Separating packages v0.3.1
meogol/Koreb pull request #103
Opened 2021-12-09 12:19 UTC by EugeneFolkast

2021-12-14 13:17 UTC, ONEPANTSU approved these changes

2021-12-14 14:17 UTC, CoNNoR51 approved these changes

2021-12-14 14:43 UTC, meogol requested changes

2021-12-14 14:43 UTC, meogol commented on iter_two/core/server/serv_socket_client.py
> +                    packages.append(len(package[last_slice_pos: last_slice_pos + slice_size]))
это не надо

2021-12-14 14:43 UTC, meogol commented on iter_two/core/server/serv_socket_client.py
> +                    pkg_counter += 1
это чистейший даблкод. Весь этот метод легко бьется на несколько методов, что позволяет сделать его более читаемым

2021-12-14 14:43 UTC, meogol commented on iter_two/core/server/serv_socket_client.py
> +            packages[0].append(len(package))
зачем 0???

2021-12-14 14:43 UTC, meogol commented on iter_two/taker/taker.py
> +                    pkg_list_for_sort.append(buffer)
это костыль. Чистейший

2021-12-14 14:43 UTC, meogol commented on iter_two/taker/taker.py
> +                        int_package += pkg_buffer_list[i] * 10 ** (len(pkg_buffer_list) - i - 1)
это можно делать в одном форе

2021-12-14 14:43 UTC, meogol commented on iter_two/taker/taker.py
> +                        send(scapy_package)
зачем слать одно и тоже несколько раз?

2021-12-14 14:45 UTC, vanotuvanov commented on iter_two/core/server/serv_socket_client.py
> +            exceed = round(len(package) / 20)
длину пакета нужно делить не на 20, а на максимальную длину сокета, те 2000

2021-12-14 20:01 UTC, EugeneFolkast commented on iter_two/core/server/serv_socket_client.py
> +            pkg_counter = 1
Сделано

2021-12-15 07:33 UTC, meogol requested changes

2021-12-15 07:33 UTC, meogol commented on iter_two/taker/taker.py
> +        # self.check_stack_thread.start()
я даже не знаю что тут сказать

2021-12-15 07:33 UTC, meogol commented on iter_two/taker/taker.py
> +                    pkg_list_for_sort.remove(pkg_list_for_sort[0])
это очень сильно путает

2021-12-15 08:02 UTC, meogol requested changes

2021-12-15 08:02 UTC, meogol commented on iter_two/taker/taker.py
> +        int_list = int_list.remove(len(int_list) - 2)
это лучше сделать срезом до len-2

2021-12-15 08:02 UTC, meogol commented on iter_two/taker/taker.py
> +                    pkg_list_for_sort = pkg_list_for_sort[:last_pkg_index]
теперь последни итем не добавляется

2021-12-15 08:10 UTC, meogol approved these changes

2021-12-15 08:10 UTC, meogol commented on iter_two/taker/taker.py
> +                    pkg_list_for_sort = pkg_list_for_sort[1:len(pkg_list_for_sort)] + pkg_list_for_sort[:0]
[1:] берет срез до конца

2021-12-15 08:11 UTC, merged